datasets:
  input_size: 512
  name: wireframe
  with_centermap_extend: false
decode:
  len_thresh: 10
  score_thresh: 0.1
  top_k: 1000
loss:
  focal_loss_level: 1
  loss_type: 1*L1
  loss_weight_dict_list:
  - sol_center_loss: 5.0
    tp_center_loss: 2.0
    tp_match_loss: 1.0
  match_sap_thresh: 3.0
  with_focal_loss: true
  with_match_loss: true
  with_sol_loss: true
model:
  model_name: mobilev2_mlsd_large
  num_classes: 1
  with_deconv: true
sys:
  cpu: false
  gpus: 1
  num_workers: 8
train:
  adam_epsilon: 1.0e-06
  batch_size: 8
  cache_to_mem: false
  data_cache_dir: ./data/wireframe_cache/
  device_ids:
  - 0
  device_ids_str: '0'
  do_train: true
  dropout: 0.1
  early_stop_n: 200
  gradient_accumulation_steps: 1
  img_dir: ./datasets/taihe_0625_hangdian_640/train/
  label_fn: ./datasets/taihe_0625_hangdian_640/train.json
  learning_rate: 0.001
  load_from: D:\PyProject\MLSD\models_mlsd\mobilev2_mlsd_large_512_bsize24\best.pth
  log_steps: 50
  lr_decay_gamma: 0.5
  milestones:
  - 40
  - 80
  - 100
  milestones_in_epo: true
  num_train_epochs: 120
  num_workers: 8
  save_dir: ./runs_mlsd
  use_step_lr_policy: true
  warmup_steps: 500
  weight_decay: 1.0e-06
  with_cache: false
val:
  batch_size: 4
  img_dir: ./datasets/taihe_0625_hangdian_640/val/
  label_fn: ./datasets/taihe_0625_hangdian_640/val.json
  val_after_epoch: 5
